### ISSUE TITLE
Crash when encoding

### ISSUE THREAD

**Issue by PetrKaleta** [rcode5/qr4r#1]
Hey, I am using your qr code encoder on Heroku (running in Sidekiq bg job). Everything is working like a charm, just today I've received report, that encoding crashed in one case and I can't see any reason why :/

```
MojoMagick command failed: convert. (Exit status: 1) 
    Command: convert  -format rgb -depth 8 -size 53x53 /tmp/mojo20131213-2-1j1ppwl.rgb -scale 1060x1060 -bordercolor "\"#ffffff\"" -border 40x40 /app/tmp/generator/qrcode20131213-2-1ilrptg.png 2>/dev/null 
  /app/vendor/bundle/ruby/2.0.0/gems/mojo_magick-0.5.3/lib/mojo_magick.rb:88:in `raw_command' 
  /app/vendor/bundle/ruby/2.0.0/gems/mojo_magick-0.5.3/lib/mojo_magick.rb:159:in `convert' 
  /app/vendor/bundle/ruby/2.0.0/gems/qr4r-0.3.5/lib/qr4r.rb:48:in `encode' 
```

Any hints?

**Comment by bunnymatic** [comment]
if you are still having issues, please let me know and upload the image that is causing issues.  I'm closing this issue
